# Site settings
title: FordSec: Security at Haverford
author: FordSec
author_avatar: https://gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=50
email: kris@cs.haverford.edu
description: "FordSec: Security Research at Haverford College"
baseurl: "" # optional
url: "https://fordsec.github.io"
#twitter_username: foo_bar
#github_username: foo_bar
github_repo: fordsec/fordsec.github.io
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
